### ISSUE TITLE
Document in-register representation of _Bool

### ISSUE THREAD

**Issue by gnzlbg** [riscv/riscv-elf-psabi-doc#107]
The in-register representation of _Bool, i.e. when booleans are passed in integer registers, is not documented. 

The SysV ABI documents:

> When stored in integer registers (except for passing as arguments), all 8 bytes of the register are significant; any nonzero value is considered `true`.

Some examples:

Ideally, here: 

```c
void write_bool(bool value, bool* ptr) {
    *ptr = value;
}
```

we should be able to just truncate the register to a 1 byte register when doing the write, without having to do any sort of comparison. In this other example: 

```c
int write_bool(bool value) {
    if (value) { return 42; } else { return 13; } 
}
```

we should be able to test the value directly. When doing a comparison, like `a == b`, ideally, we should be able to do a bitwise comparison, and produce a bool directly.

I don't know of any wording that satisfies all three.

**Comment by jim-wilson** [comment]
Which exact SysV document are you referring to?  Please give a reference, such as a URL.

Please don't confuse how the vector extension hardware works with how the ISO C standard works.  _Bool is always 0 or 1 as per the ISO C standard.

**Comment by gnzlbg** [comment]
Hi @jim-wilson, thank you for the feedback, and sorry for the missing link. 

> Which exact SysV64 ABI are you referring to? 

The x86-64-psABI, see: https://github.com/hjl-tools/x86-psABI/wiki/x86-64-psABI-1.0.pdf although in the wiki here you can find draft versions with bug fixes: https://github.com/hjl-tools/x86-psABI/wiki/ . Also there you can also find the Intel386 psABI, for which the following also applies.

Quoting the document, page 15:

> When stored in integer registers (except for passing as arguments), all 8 bytes of the register are significant; any nonzero value is considered true.

**Comment by gnzlbg** [comment]
So maybe I misread that part, and the "except for passing as arguments" means that, when passing as arguments, the _Bool must be 0 or 1 in the ABI ?

**Comment by jim-wilson** [comment]
The x86-64 psABI is using boolean in some places and _Bool in other places.  It says that a boolean uses the whole register except when passing as arguments.  Then it stays that a _Bool argument has only 1 valid byte, and the other bytes are unspecified.

I'm seeing similar behavior with gcc and the RISC-V port, but we may not want to over specify this.  Some of this may be gcc implementation issues.  We don't have instructions to compare or manipulate single bytes, other than load/store, so it makes sense to use the whole register for a boolean/_Bool.  We do type conversions in the prologue, and since a boolean/_Bool is one byte, we may only use one byte of the input value.

Here is an example.  Note in the unoptimized code, we use only a single byte of the argument.  In the optimized code, we use the whole register.  But since a boolean/_Bool should always be 0 or 1, these give the same result.
rohan:2184$ cat tmp3.c
int sub (_Bool i) { return i; }
rohan:2185$ riscv32-unknown-elf-gcc -S tmp3.c
rohan:2186$ cat tmp3.s
	.file	"tmp3.c"
	.option nopic
	.text
	.align	1
	.globl	sub
	.type	sub, @function
sub:
	addi	sp,sp,-32
	sw	s0,28(sp)
	addi	s0,sp,32
	mv	a5,a0
	sb	a5,-17(s0)
	lbu	a5,-17(s0)
	mv	a0,a5
	lw	s0,28(sp)
	addi	sp,sp,32
	jr	ra
	.size	sub, .-sub
	.ident	"GCC: (GNU) 8.3.0"
rohan:2187$ riscv32-unknown-elf-gcc -O -S tmp3.c
rohan:2188$ cat tmp3.s
	.file	"tmp3.c"
	.option nopic
	.text
	.align	1
	.globl	sub
	.type	sub, @function
sub:
	ret
	.size	sub, .-sub
	.ident	"GCC: (GNU) 8.3.0"
rohan:2189$ 

I think the only way you can get a boolean/_Bool that isn't 0 or 1 is to write code that somehow avoids an explicit conversion between integer and boolean/_Bool, and if you do that, then you are likely to get unpredictable results.  Here is an example.  These two programs return different results for both x86-64 and RISC-V.
rohan:2189$ more tmp.c
#include <stdio.h>
int sub (_Bool i) { return i; }
int sub2 (int i) { return sub (i); }
int main (void) { printf ("%d\n", sub2 (0xff00)); return 0; }
rohan:2190$ more tmp2.c
#include <stdio.h>
int sub (i) _Bool i; { return i; }
int sub2 (int i) { return sub (i); }
int main (void) { printf ("%d\n", sub2 (0xff00)); return 0; }
I'm not sure if that is a gcc bug or a language feature, but I'd recommend against using old style function declarations in general, so I don't think we need to define a "right" result here.
