### ISSUE TITLE
Syscall ABI for RV32E

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-elf-psabi-doc#11]
Current syscall abi implement in newlib is pass argument in $a0~$a3 and syscall number in $a7[1]

However $a7 is not avariable in RV32E, so let put in $a4, $a5?

[1] https://github.com/riscv/riscv-newlib/blob/riscv-newlib-2.4.0/libgloss/riscv/machine/syscall.h

**Comment by sorear** [comment]
How about `t0` or `t1`?  Then we could change Linux as well, and it'd be slightly cleaner to not have the call selector stepping on one of the argument registers.

We would still need to define what the calling convention is on RV32E.  There are tradeoffs that happen differently with just 15 registers…

**Comment by aswaterman** [comment]
From the manual: "The privileged architecture of an RV32E system can include user mode as well as machine mode, and the Mbare, Mbb, and Mbbid memory management schemes described in Volume II."

RV32E is meant for embedded systems that don't host an OS, so the choice of a7 doesn't matter.  If you can afford the primary and secondary storage necessary to host Linux, you can afford the additional 16 registers (and probably will get better energy per operation from having them).  My preference is to take no action on this matter.

If we did take action, a5 would not be ideal, since mmap takes 6 args and so already uses a5.  t0 is probably fine.

**Comment by kito-cheng** [comment]
Humm, so we will implement that in `t0` for newlib and gdb sim.

@sorear RV32E seem only 3 callee save register(and 1 for $sp), do you think need to make it more balance?

**Comment by sorear** [comment]
@kito-cheng I have absolutely no idea.  Build SPEC with various ratios of caller to callee saves and pick whichever one minimizes code size?

**Comment by aswaterman** [comment]
My work on RVC resulted in x8-15 being s0-1 and a0-5.  Point being, having RVC target 2 saved and 6 argument registers minimized code size, moreso than 3 saved and 5 argument, for example.  So I'd leave it as-is.

Also, we want the register map for RV32E to match RV32I if at all possible to minimize confusion.

**Comment by michaeljclark** [comment]
Just noting that the PLT header and stubs use `t3` for shared library calls. I wonder if the stubs can be reworked to use `t0` through `t2`. This is a separate issue to the syscall ABI.

**Comment by aswaterman** [comment]
I highly doubt dynamic linking will be popular on RV32E systems, but yeah, it looks possible.

**Comment by kito-cheng** [comment]
It should be target / OS specific things, so I think we are not going to document on psABI.
