### ISSUE TITLE
Calling Convention for Half-Precision Floating-point Values

### ISSUE THREAD

**Issue by lenary** [riscv/riscv-elf-psabi-doc#118]
I would like to clarify the calling convention for half-precision floating-point values.

With ILP32 and LP64, they are passed using the integer calling convention, either in integer registers, or on the stack. This is clear and reasonable.

What about with ILP32F/D or LP64F/D/Q? The FP calling convention says:
> A real floating-point argument is passed in a floating-point argument register if it is no more than FLEN bits wide and at least one floating-point argument register is available.

No exception is carved out for half-precision fp values (which are less than FLEN bits wide in these calling conventions) in the hard floating-point calling convention, so that suggests they should be passed in the fp registers "whenever possible". 

However, there are no half-precision instructions in RISC-V F/D extensions, not even to take a half-precision value in an integer register and move/convert it into a single precision FP register (or vice versa).

This suggests we should explicitly note that it is not possible to pass half-precision FP values in FP registers in the hardware floating-point calling conventions defined so far.

Have I missed anything, or should I go ahead and start a pull-request? Comments welcome!

**Comment by jim-wilson** [comment]
GCC does not support half-precision float for RISC-V.  Half-precision float is only supported for targets that have half-precision float instructions, which at present is arm, aarch64, and AMD GCN.  There are a few targets that have half-precision float vectors, but not scalar half-precision float, which I am ignoring as not relevant.  The proposed RISC-V Vector extension has half-precision float vectors, but again, I think that is not relevant.

There is a proposal to add half-float support to the RISC-V architecture.  The K extension letter was proposed for this I believe.  So if a target supports the half-precision float scalar extension, then gcc will add support for half-precision floats, and since we will have instructions to copy them into fp registers, it would be reasonable and sensible to allow them to be passed in FP registers.

But at present, since there is no half-precision float type, we don't need ABI support for them.
rohan:2087$ cat tmp.c
_Float16 t;
rohan:2088$ riscv64-unknown-linux-gnu-gcc -O -S tmp.c
tmp.c:1:1: error: '_Float16' is not supported on this target
 _Float16 t;
 ^~~~~~~~
rohan:2089$ 

Just experimenting with an x86_64-linux clang, I see that unlike gcc it allows _Float16, but then I get a link failure for a missing _gnu_h2f_ieee function.  It appears that this function is supposed to be in the clang runtime library, but maybe my Ubuntu 18.04 clang 7 version is too old for this to work.  I don't have a riscv clang to experiment with.

For now, what the ABI says about half-precision float is irrelevant for gcc, as long as it isn't required to support it.  Passing them in int registers is reasonable.  In the future, if/when the half-precision extension is supported, we should allow them to be passed in FP registers.  For gcc, there will be no conflict because we won't support half-precision float unless there is hardware for it.  For clang, it looks like there could be a conflict, and half-precision float will be passed in either int or fp registers depending on the hardware.  It isn't obvious how to resolve that conflict.  We might need new ABI definitions for that, like ilp32dh, where for gcc ilp32d and ilp32dh will be compatible, but for clang they will not be compatible.

**Comment by lenary** [comment]
Ok, I think it's worth carving out an exception in the current ABIs for half-precision values, to ensure that GCC and Clang can remain compatible if someone specifies "ilp32d" or "ilp32f", with or without half-precision FP hardware. 

I shall work on a pull-request. It's likely that we would be on firmer ground if we specified exactly the floating point kinds we expect to be passed in FP registers for the ABI (i.e ILP32F/LP64F pass only 32-bit fp values in fp registers, and ILP32D/LP64D pass only 32- and 64-bit fp values in fp regs).

Later, if a half-precision extension is officially ratified, we can add ABIs for hardware half-precision floats if we feel that's needed (as you suggest, adding "H" to the end of the ABI makes sense).

Aside: I first noticed the odd calling convention in the `_gnu_h2f_ieee` function (where we were testing some half-precision FP support).

**Comment by lenary** [comment]
Ah, ok, I see how everything fits together:
- C17 does not define any half-precision FP types.
- LLVM IR does internally have a `half` datatype, but Clang will not emit it for RISC-V.
- Other backends may emit it, but they won't get good interoperation with C according to this psABI.

So I won't carve out the exception, as it's covered under "real floating-point values"
