### ISSUE TITLE
Clarity on weak, undefined symbols in non-PIC code

### ISSUE THREAD

**Issue by bsdjhb** [riscv/riscv-elf-psabi-doc#126]
The FreeBSD kernel uses weak symbols in its uart(4) driver as well as in numerous other cases for linker sets.  These symbols are not functions invoked via call, but are pointers to data.  In some cases these weak symbols may be undefined when linking the kernel which FreeBSD assumes will result in a value of NULL.  This has been true with all other architectures FreeBSD has run on to date.  The bfd linker also seemingly enforces this.

When linking the kernel with lld, I ran into linker errors due to the resolved symbol being out of range for the PC-relative relocations being used.  I proposed a patch to lld at https://reviews.llvm.org/D71100 but there are some questions of if the semantics in that change are the desired semantics.

From comments in #98 it seems that it is assumed (but not stated) that R_RISCV_CALL relocations against undefined weak symbols should be resolved to an absolute address of 0 rather than a PC-relative address.

However, for data addresses, it is conceivable that a data address should be indirected through a GOT entry to permit overriding (e.g. if a symbol is provided at runtime via LD_PRELOAD or a newer version of a library than was available at the time a binary was linked) while still permitting a value of zero to be used if the binary is running at a "high" virtual address.

**Comment by jim-wilson** [comment]
Given the testcase
extern int i __attribute__ ((weak));
int main (void) { return i; }
compiling with gcc -O I get
000000000001043e <main>:
   1043e:	000007b7          	lui	a5,0x0
   10442:	0007a503          	lw	a0,0(a5) # 0 <_PROCEDURE_LINKAGE
_TABLE_-0x10360>
   10446:	8082                	ret
compiling with gcc -O -fpie I get
000000000001046e <main>:
   1046e:	00002797          	auipc	a5,0x2
   10472:	bb27b783          	ld	a5,-1102(a5) # 12020 <i>
   10476:	4388                	lw	a0,0(a5)
   10478:	8082                	ret
So it is indirecting through the got.  This fails with a segfault when I run it.  But if I preload a shared library that defines the variable i, then it returns that value.
hifiveu017:1073$ ./a.out
Segmentation fault (core dumped)
hifiveu017:1074$ cat tmp2.c
int i = 10;
hifiveu017:1075$ gcc --shared -fpic tmp2.c -o libtmp.so
hifiveu017:1076$ LD_PRELOAD=`pwd`/libtmp.so ./a.out
hifiveu017:1077$ echo $?
10
hifiveu017:1078$ 

Bfd has special support for the case where we are calling an undefined weak function.  We rewrite the call instruction to be x0 relative, and ignore the auipc result.  This is in bfd/elfnn-riscv.c in riscv_elf_relocate_section in the R_RISCV_CALL case.  We don't need special support for direct references to variables as lui/lw can always reach address 0.

With gcc -O -mcmodel=medany I get
000000000001043e <main>:
   1043e:	ffff0517          	auipc	a0,0xffff0
   10442:	bc252503          	lw	a0,-1086(a0) # 0 <_PROCEDURE_LIN
KAGE_TABLE_-0x10360>
   10446:	8082                	ret
which looks like a bug no one has reported yet, since this can fail if the load address is too high.  gcc -O -mcmodel=medany -fpie gives the same code as above for the -fpie case which is OK, because the got will be in range no matter where the code is loaded.

I can't really comment on the llvm/lld stuff, but it is true that in the bfd ld, there is no standard on how to handle undefined weak, and some targets handle it differently than others.  I think arm converts a call to undefined weak to a call to the next instruction for instance.  For the RISC-V bfd port, I've just been forcing everything to 0, as I think that is the easiest to understand, even if I have to rewrite instructions to reach an address of 0.

And yes, the linker should be able to handle references to undefined weak, even if the psabi doesn't require a particular solution.  It isn't clear if we need a psabi rule for this.  For the call case, the code should never be executed in properly written code, so it shouldn't matter much what the call is resolved to.  Only that it has to be resolved to something for the link to complete.

**Comment by jrtc27** [comment]
For the medany case it's fine, your example gives:

```
000000000001040c <main>:
   1040c:	ffff0797          	auipc	a5,0xffff0
   10410:	bf478793          	addi	a5,a5,-1036 # 0 <_PROCEDURE_LINKAGE_TABLE_-0x10330>
   10414:	4388                	lw	a0,0(a5)
   10416:	8082                	ret
```

for my version of GCC, but with `-Wl,-Ttext-segment=0xc0000000 -nostdlib` (since the system crtbegin.o was not built with medany), gives:

```
00000000c00000d4 <main>:
    c00000d4:	000007b7          	lui	a5,0x0
    c00000d8:	00078793          	mv	a5,a5
    c00000dc:	4388                	lw	a0,0(a5)
    c00000de:	8082                	ret
```

BFD does the rewriting from PC-relative to absolute when required.

**Comment by jrtc27** [comment]
AArch64, for example, does do what you might expect though and forces potentially-undefined weak symbols to go via the GOT (it has no equivalent of medlow), and it feels like we should probably do the same to avoid the need to do so much rewriting. Unfortunately, neither `la` nor `lla` let you do this as, being non-fPIC/fPIE, both would expand to auipc/add, but that can be easily resolved by making `-mcmodel=medany` imply `as -pic`/`.option pic` and using `la` for these symbols.

**Comment by Nelson1225** [comment]
I think the reason is that the current GNU linker still try to use the pc-relative if the range is enough.

* riscv_zero_pcrel_hi_reloc in the bfd/elfnn-riscv.c: 1634

  /* If it's possible to reference the symbol using auipc we do so, as that's
   * more in the spirit of the PC-relative relocations we're processing.  */
  bfd_vma offset = addr - pc;
  if (ARCH_SIZE == 32 || VALID_UTYPE_IMM (RISCV_CONST_HIGH_PART (offset)))
    return FALSE;

  /* If it's impossible to reference this with a LUI-based offset then don't
   * bother to convert it at all so users still see the PC-relative relocation
   * in the truncation message.  */
  if (ARCH_SIZE > 32 && !VALID_UTYPE_IMM (RISCV_CONST_HIGH_PART (addr)))
    return FALSE;

And this behavior is reasonable to me.  Therefore, if the pc-relative range is enough, we should get the Jim's result. Otherwise, we should get jrtc27's result as expected.

However, I get another different result when I use the upstream LD.
```
0000000000010182 <main>:
   10182:       00002503                lw      a0,0(zero) # 0 <register_fini-0x100e8>
   10186:       8082                    ret
```
Since we have optimized LUI and AUIPC relaxations for undefined weak symbols now.  For the LUI and AUIPC relaxations, since the symbol value of an undefined weak symbol is always be zero, we can optimize the patterns into a single LI/MV/ADDI/LW/SW instruction.  Looks like the problem was accidentally solved by this optimization.

**Comment by Nelson1225** [comment]
The source code is same as above:
`extern int i __attribute__ ((weak));  int main (void) { return i; }`

| | x86-64 linux gcc | AArch64 linux gcc | Riscv-64 linux gcc|
| --- | --- | --- | --- |
|-fno-pic | \<main\>: <br> push  %rbp <br> mov    %rsp,%rbp <br> **mov    -0x66a(%rip),%eax        # 0** <br> pop    %rbp <br>  retq <br> nopl   0x0(%rax) |  \<main\>: <br> **adrp    x0, 0** <br> **add     x0, x0, #0x7f8** <br>ldr     x0, [x0] <br> ldr     w0, [x0] <br> ret <br><br> **0+0x7f8 is Rodata, the value is zero** | \<main\>: <br>addi    sp,sp,-16 <br> sd      s0,8(sp) <br> addi    s0,sp,16 <br> **lw      a5,0(zero) # 0** <br>mv      a0,a5 <br> ld      s0,8(sp) <br> addi    sp,sp,16 <br> ret
| -fPIC | \<main\>: <br> push   %rbp <br> mov    %rsp,%rbp <br> **mov    0x200935(%rip),%rax        # 200fe0 <i>** <br> mov    (%rax),%eax <br> pop    %rbp <br> retq <br> nop <br> <br> **0x200fe0 is in GOT table** | \<main\>: <br> **adrp    x0, 10000**  <br> **ldr     x0, [x0, #4072]** <br> ldr     w0, [x0] <br> ret <br> <br> **0x10000+4072 = 0x10fbb is in GOT table** | \<main\>: <br> addi    sp,sp,-16 <br> sd      s0,8(sp) <br> addi    s0,sp,16 <br> **auipc   a5,0x2** <br> **ld      a5,-1100(a5) # 12020 <i>** <br>   lw      a5,0(a5) <br>mv      a0,a5 <br> ld      s0,8(sp) <br>addi    sp,sp,16 <br> ret <br> <br> **0x12020 is in GOT table**
 

> Note that the x86-64 and AArch64 gcc are set **--enable-default-pie** configure, but RISCV gcc aren't.

Looks like RISCV have the same behavior as x86-64.  With -fno-pic, Aarch64 put the weak symbol into  Rodata with zero value, and if I set **-mcmodel=large**, the weak symbol will be put into the literal pools.  Therefore I think AArch64 and x86-64 not only force the undefined weak symbols to go via the GOT, but also all global symbols since the GCC enable the PIC/PIE by default.  Please let me know if I missed anything, thanks :)

**Comment by jim-wilson** [comment]
Embedded elf systems don't have a dynamic linker or a got, so forcing references via the got is not a solution that works for all targets.  Since we have to do the instruction rewriting for embedded elf systems anyways, I don't see any point of trying to handle linux differently.  The current bfd ld behavior for undefined weak is working fine, and does not need changing.

**Comment by jrtc27** [comment]
> Embedded elf systems don't have a dynamic linker or a got, so forcing references via the got is not a solution that works for all targets. Since we have to do the instruction rewriting for embedded elf systems anyways, I don't see any point of trying to handle linux differently. The current bfd ld behavior for undefined weak is working fine, and does not need changing.

Just because there's a GOT doesn't mean you need dynamic relocations for it. If you statically link, you will have a GOT section whose contents has already been filled in at link time, exactly the same as if you declare a global variable `int *p = &foo`.

**Comment by jrtc27** [comment]
> The source code is same as above:
> `extern int i __attribute__ ((weak)); int main (void) { return i; }`
> 
> x86-64 linux gcc	AArch64 linux gcc	Riscv-64 linux gcc
> -fno-pic	<main>: 
> push %rbp 
> mov %rsp,%rbp 
> **mov -0x66a(%rip),%eax # 0** 
> pop %rbp 
> retq 
> nopl 0x0(%rax)	<main>: 
> **adrp x0, 0** 
> **add x0, x0, #0x7f8** 
> ldr x0, [x0] 
> ldr w0, [x0] 
> ret 
> 
> **0+0x7f8 is Rodata, the value is zero**	<main>: 
> addi sp,sp,-16 
> sd s0,8(sp) 
> addi s0,sp,16 
> **lw a5,0(zero) # 0** 
> mv a0,a5 
> ld s0,8(sp) 
> addi sp,sp,16 
> ret
> -fPIC	<main>: 
> push %rbp 
> mov %rsp,%rbp 
> **mov 0x200935(%rip),%rax # 200fe0 ** 
> mov (%rax),%eax 
> pop %rbp 
> retq 
> nop 
> 
> **0x200fe0 is in GOT table**	<main>: 
> **adrp x0, 10000** 
> **ldr x0, [x0, #4072]** 
> ldr w0, [x0] 
> ret 
> 
> **0x10000+4072 = 0x10fbb is in GOT table**	<main>: 
> addi sp,sp,-16 
> sd s0,8(sp) 
> addi s0,sp,16 
> **auipc a5,0x2** 
> **ld a5,-1100(a5) # 12020 ** 
> lw a5,0(a5) 
> mv a0,a5 
> ld s0,8(sp) 
> addi sp,sp,16 
> ret 
> 
> **0x12020 is in GOT table**
> > Note that the x86-64 and AArch64 gcc are set **--enable-default-pie** configure, but RISCV gcc aren't.
> 
> Looks like RISCV have the same behavior as x86-64. With -fno-pic, Aarch64 put the weak symbol into Rodata with zero value, and if I set **-mcmodel=large**, the weak symbol will be put into the literal pools. Therefore I think AArch64 and x86-64 not only force the undefined weak symbols to go via the GOT, but also all global symbols since the GCC enable the PIC/PIE by default. Please let me know if I missed anything, thanks :)

1. `-fPIC` is different from `-fPIE`. They both imply position-independence, but `-fPIC` also implies symbol preemptibility, which forces any non-static (/non-protected) variable to go via the GOT.

2. You need to be very careful about what you're testing here. For x86 executables, the default code model is `small`, which is the same as RISC-V's `medlow` in semantics (guaranteed to be the low 2 GiB), hence its 32-bit PC-relative instruction will always work. The only model that doesn't make that assumption for the executable is `large`, which generates a `movabsq` instruction, ie puts the 64-bit absolute address inline. There is not an equivalent however of `medany`; the only way to generate position-independent code is via `-fPIE`/`-fPIC`, both of which use the GOT.

3. You're looking at the linked output for all of these. For x86 and AArch64 this isn't so much of an issue, but for RISC-V you see the result of the linker relaxations and rewriting, so you have no idea what code the compiler actually generated.

**Comment by jim-wilson** [comment]
Changing bfd ld because lld is broken makes no sense to me.  I think this discussion has gone way off topic.

**Comment by Nelson1225** [comment]
Thanks for your feedback @jrtc27 :)

> 1. `-fPIC` is different from `-fPIE`. They both imply position-independence, but `-fPIC` also implies symbol preemptibility, which forces any non-static (/non-protected) variable to go via the GOT.

Agree with this.  It seems to me that the most difference between PIC and PIE is that PIC need dynamic linker to help to resolve the symbols in the GOT, and PIE don't need it because all symbols should be known and resolved in the linker (ld/lld).  If we use non-position-independence code in PIE, then we need to add RELATIVE relocation to let ELF loader can fix the absolute address access after random loading the executable.

> 2. You need to be very careful about what you're testing here. For x86 executables, the default code model is `small`, which is the same as RISC-V's `medlow` in semantics (guaranteed to be the low 2 GiB), hence its 32-bit PC-relative instruction will always work. The only model that doesn't make that assumption for the executable is `large`, which generates a `movabsq` instruction, ie puts the 64-bit absolute address inline. There is not an equivalent however of `medany`; the only way to generate position-independent code is via `-fPIE`/`-fPIC`, both of which use the GOT.

Thanks for this. 

> 3. You're looking at the linked output for all of these. For x86 and AArch64 this isn't so much of an issue, but for RISC-V you see the result of the linker relaxations and rewriting, so you have no idea what code the compiler actually generated.

Thanks for the reminder.  I skip some details about what I have tested, but it doesn't mean I have no idea what the code looks like before relaxation and rewriting :)


I also have seen your discussion in the LLVM page.  Seems like you want to use part of position independent code to resolve the out of range of undefined weak symbol in RV64 toolchain.  But this need extra spaces (you use GOT), which can be accessed in the pc-relative range, to keep the zero value.  I think the idea is good, but use GOT and part of pie may become confusing.  I suppose not only the undefined weak symbol is out of range for pc-relative, but also all 64-bit symbols may .  This should be the large model issue I think.  AArch use the literal pools to resolve the problems about large model, and the literal pools are the extra spaces to hold the symbol address. 

Fortunately the undefined weak symbol is always be zero for embedded elf systems.  Therefore, Jim's rewrite solution is more simple and don't need any extra spaces for the **undefined weak symbol** which is out of range.  It seems to me that your idea (extra spaces to hold value) is a bit like one of the solution for large model :)

**Comment by MaskRay** [comment]
-fpic vs -fPIC, -fpie vs -fPIE: I think they are only relevant on ppc32 and sparc. We can just ignore them for other architectures.

-fpic vs -fpie: the code generation differences are only for defined symbols, due to preemptibility. There is no difference for undefined symbols.

We should keep in mind that semantics of weak undefined symbols are largely unspecified in specifications, and varying among implementations. We should not encourage their uses, even on embedded elf systems.

`R_RISCV_RELATIVE` is emitted for:

(1) a GOT slot whose symbol is non-preemptible and relative (!SHN_ABS)
(2) a symbolic relocation (R_RISCV_32 on rv32, R_RISCV_64 on rv64) referencing a non-preemptible symbol

An undefined weak symbol (st_shndx=SHN_UNDEF, st_value=0, bind: STB_WEAK)'s "value" is not a constant.
It depends on the relocation which evaluates it.

For branch relocations, they don't really evaluate the address. The address is insignificant, and one architectures where branch/call instructions have limited range, the target can be freely redirected to a call stub/thunk/veneer. The resolved target does not really matter. Calling such instructions should be clearly an undefined behavior. In practice, we can make a decision to make overflow less likely. This is code model related, so resolving to the same instruction can be a good choice. There is also a trade-off to make it look good in a disassembler, but this benefit is usually overthrown by the previous one.

For non-branch relocations. There are several types:

- Absolute: 0
- Relative (most commonly PC-relative. Relative to other things are possible but similar): -no-pie: 0; -pie or -shared: load base
    Compilers should not emit PC-relative relocationas in -fpic/-fpie mode.
- GOT: lld's rule is simple and architecture independent. -no-pie and -pie: GOT pre-filled with 0; -shared: GOT entry with a GLOB_DAT.
  GNU ld's rules are complex.
 aarch64-linux-gnu-ld. -no-pie: GOT pre-filled with 0; -pie or -shared: GLOB_DAT
 x86_64-linux-gnu-ld. -no-pie: GOT pre-filled with 0 (GOTPCRELX relaxations apply); -pie or -shared: GLOB_DAT (if -z nodynamic-undefined-weak, use a pre-filled GOT)
  I don't think -z nodynamic-undefined-weak was invented for a good reason.

For Absolute and Relative -no-pie, making it clear in psABI is fine. For others, especially branch relocations, I hope there can be lots of leeway in the implementations. In particular, I don't want to see things that make lld implementation constrained.

For https://reviews.llvm.org/D71100 , I have some different idea to make it work. @bsdjhb are you ok with me taking over it? I may do the following:

R_RISCV_CALL (call foo): resolve to same pc
R_RISCV_BRACH (beq a0, a1, foo): resolve to same pc
R_RISCV_JAL (jal x0, foo): resolve to same pc
R_RISCV_RVC_JUMP (c.j foo): resolve to same pc
R_RISCV_RVC_BRANCH (c.beqz a0, foo): resolve to same pc

Allowing some while disallowing others (as D71100 does) is probably not very necessary.

**Comment by Nelson1225** [comment]
Thanks for your descriptions, @jim-wilson, @jrtc27, @MaskRay.  These are helpful :)

**Comment by bsdjhb** [comment]
@MaskRay I'm fine with you taking over the review.  The use case I'm tripping over in FreeBSD's kernel is only for data references and not branches.  I had only included the branch cases to try to make the patch complete and give errors or warnings if a user was trying to do something that wasn't going to be handled.

**Comment by MaskRay** [comment]
```
echo 'extern long v; long foo() { return v; }' > a.c
echo 'long b;' > b.c
riscv64-linux-musl-gcc -mcmodel=medany -fno-pic -c -O a.c  # PC-relative
riscv64-linux-musl-gcc -mcmodel=medany -fpic -c -O b.c     # GOT relocation
riscv64-linux-musl-gcc -mcmodel=medany -fpic -shared -O b.c -o b.so  # GOT relocation

riscv64-linux-musl-ld a.o b.o -o a.local
riscv64-linux-musl-ld a.o b.so -o a.external
```

`-mcmodel=medany -fno-pic` generates PC-relative code sequence, which may cause a copy relocation if the variable is preemptible (defined externally):

```
% riscv64-linux-musl-readelf -r a.external

Relocation section '.rela.dyn' at offset 0x218 contains 1 entry:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000012008  000100000004 R_RISCV_COPY      0000000000012008 v + 0
```

GNU ld has logic to rewrite the code sequence to (set a5 to 0).

```
% riscv64-linux-musl-objdump -d a.local
...
   200000078:   000007b7                lui     a5,0x0
   20000007c:   00078793                mv      a5,a5
```

I think we have several choices:

1. Consider undefined weak symbols unsupported in -mcmodel=medany -fno-pic mode.
   Then, lld can error `relocation R_RISCV_PCREL_HI20 out of range` as it does now.
   The lld patch https://reviews.llvm.org/D71100 will not be needed.
2. Let `-mcmodel=medany -fno-pic` emit `.L: auipc auipc a5,%got_pcrel_hi(v); ld a5,%pcrel_lo(.L)(a0)`
   This unifies `-fno-pic` and `-fpic`. Then, relax `R_RISCV_GOT_PCREL` to PC-relative (think of R_X86_64_GOTPCRELX and PPC64 toc-indirect to toc-relative relaxation).
   On the LLVM codegen side, I have a patch: https://reviews.llvm.org/D72056

   We can make `-mcmodel=medlow -fno-pic` emit `%got_pcrel_hi` as well. Then, all 4 modes will be unified.


Note that aarch64 and ppc64 use either absolute or GOT variant, but not PC relative. So they can resolve PC-relative relocations to an undefined weak symbol to an arbitrary address.

```
gcc -fno-pic

aarch64 -mcmodel={small,large}: GOT variant (.rodata.cst8)
ppc64 -mcmodel={small,large}: GOT variant (.toc)
x86_64 -mcmodel=small: PC relative
x86_64 -mcmodel=large: absolute
riscv -mcmodel=medlow: absolute
riscv -mcmodel=medany: PC relative

clang -fno-pic

aarch64 -mcmodel=small: GOT variant (.rodata.cst8)
aarch64 -mcmodel=large: absolute (R_AARCH64_MOVW_UABS_G0_NC+R_AARCH64_MOVW_UABS_G1_NC+R_AARCH64_MOVW_UABS_G2_NC+R_AARCH64_MOVW_UABS_G3)
ppc64 -mcmodel={small,large}: GOT variant (.toc)
riscv -mcmodel=medlow: absolute (R_RISCV_HI20+R_RISCV_LO12_I)
riscv -mcmodel=medany: PC relative (R_RISCV_PCREL_HI20+R_RISCV_PCREL_LO12_I)
```

**Comment by jrtc27** [comment]
> ```
> echo 'extern long v; long foo() { return v; }' > a.c
> echo 'long b;' > b.c
> riscv64-linux-musl-gcc -mcmodel=medany -fno-pic -c -O a.c  # PC-relative
> riscv64-linux-musl-gcc -mcmodel=medany -fpic -c -O b.c     # GOT relocation
> riscv64-linux-musl-gcc -mcmodel=medany -fpic -shared -O b.c -o b.so  # GOT relocation
> ```

You want to be looking at `-fpie` not `-fpic`, since the latter also has implications about symbol preemption, although I don't believe it changes the story here.

> I think we have several choices:
> 
> 1. Consider undefined weak symbols unsupported in -mcmodel=medany -fno-pic mode.
>    Then, lld can error `relocation R_RISCV_PCREL_HI20 out of range` as it does now.
>    The lld patch https://reviews.llvm.org/D71100 will not be needed.

This may be a choice, but like many, it's not an acceptable one, and makes RISC-V LLD break real world code that works on every other supported architecture. Please stop bothering to suggest this, I'm tired of having to repeat myself.

> 2. Let `-mcmodel=medany -fno-pic` emit `.L: auipc auipc a5,%got_pcrel_hi(v); ld a5,%pcrel_lo(.L)(a0)`
>    This unifies `-fno-pic` and `-fpic`. Then, relax `R_RISCV_GOT_PCREL` to PC-relative (think of R_X86_64_GOTPCRELX and PPC64 toc-indirect to toc-relative relaxation).
>    On the LLVM codegen side, I have a patch: https://reviews.llvm.org/D72056
>    We can make `-mcmodel=medlow -fno-pic` emit `%got_pcrel_hi` as well. Then, all 4 modes will be unified.

This works, although it is unfortunate that the assembler does not have a macro for this. Perhaps `-mcmodel=medany` should be *assembled* with `-fpic` so that `la` uses the GOT? It is a shame that `la`'s behaviour was made conditional on `-fpic` rather than having it always use the GOT, given that `lla` can always be used to avoid the GOT.

> If we always emitted a GOT-generating relocation, we would not need
> ```c
> // binutils-gdb/bfd/elfnn-riscv.c
> 	case R_RISCV_CALL:
> 	  /* Handle a call to an undefined weak function.  This won't be
> 	     relaxed, so we have to handle it here.  */
> 	  if (h != NULL && h->root.type == bfd_link_hash_undefweak
> 	      && h->plt.offset == MINUS_ONE)
> 	    {
> 	      /* We can use x0 as the base register.  */
> 	      bfd_vma insn = bfd_get_32 (input_bfd,
> 					 contents + rel->r_offset + 4);
> 	      insn &= ~(OP_MASK_RS1 << OP_SH_RS1);
> 	      bfd_put_32 (input_bfd, insn, contents + rel->r_offset + 4);
> 	      /* Set the relocation value so that we get 0 after the pc
> 		 relative adjustment.  */
> 	      relocation = sec_addr (input_section) + rel->r_offset;
> 	    }
> ```

Yes you would. Function calls are currently always PC-relative, regardless of `-fpie`/`-fpic`, as we have PLT stubs to handle preemption.
