### ISSUE TITLE
Should gp be aligned?

### ISSUE THREAD

**Issue by knightsifive** [riscv/riscv-elf-psabi-doc#141]
The current document does not specify any alignment constraints on `gp`, the global pointer (an address).

**Comment by ebahapo** [comment]
The psABI would define the `gp` to have the same alignment restriction as the stack.  For the motivation behind restricting the alignment for the latter likely also applies to the former.

**Comment by aswaterman** [comment]
I might be missing something, but I think the important thing is that the sections to which gp points must be aligned.  Since gp is only referenced by linker relaxation, I can't see why its alignment matters.

**Comment by knightsifive** [comment]
What was the reasoning for stack-pointer alignment? Just because of `C.ADDI16SP`, or is this putting the plow before the oxen?

**Comment by aswaterman** [comment]
quad-precision FP; ABI interactions with pairs of XLEN-sized values in RV64; general experience that people regret not having more generous stack alignment once they start trying to do SIMD stuff

**Comment by knightsifive** [comment]
Well in my opinion none of these reasons seem particularly relevant to GP-alignment.

**Comment by ebahapo** [comment]
> I might be missing something, but I think the important thing is that the sections to which gp might refer must be aligned. Since gp is only referenced by linker relaxation, I can't see why its alignment matters.

Yes. However, lest someone roll up their own start up code or linker script, this restriction should be made explicit in order to support future data types as large as 128b.  

So, a side effect of the small data section alignment is that the `gp` will also inherit its alignment, since its current defined to be 2KiB from the beginning of the section.  However, tool developers and advanced users might roll their own tools and linker scripts and need to know of any such restrictions, if compatibility with other development tools is to be maintained.

**Comment by ebahapo** [comment]
> quad-precision FP; ABI interactions with pairs of XLEN-sized values in RV64; general experience that people regret not having more generous stack alignment once they start trying to do SIMD stuff

Intel had to grow the required stack alignment as new ISA extensions were added...

**Comment by ebahapo** [comment]
> Well in my opinion none of these reasons seem particularly relevant to GP-alignment.

Historically, other ISAs had to restrict the alignment of the base of the global data area, AKA `_SDA_BASE_`, because the offsets in load and store instructions was shifted by the transfer size.  Then, the alignment would be that of the largest transfer size possible or the largest software data type, usually one up.

However, RV doesn't scale the offset in loads and stores, so it's not strictly necessary to restrict the alignment for the `gp`. 

In most cases, the alignment of the section where `_SDA_BASE_` is defined will lead to it being aligned as well.

**Comment by knightsifive** [comment]
My opinion is that the ISA mandates the appropriate instruction alignment, so we don't have to say anything about "text" sections in the ABI. Regarding "data" sections, the ABI (or its intent as I understand it) mandates the C language alignment requirements. So there can be no misaligned loads/stores. (You could trick the compiler into generating them, e.g., with misaligned pointer dereference, but this is UB.)  You can imagine countless ways of breaking these mandates with pathological compilers and link scripts. I don't think it's the ABI's job to spell this out.

My opinion would change in the case that a stricter alignment is needed to overcome a limitation of the available addressing modes. (However, I don't have a concrete example of this.)

**Comment by ebahapo** [comment]
Indeed, I don't think that there's any G instruction that restricts the offset.  Does any instruction in other extensions do?

**Comment by ebahapo** [comment]
There may be sensible reasons other than required by the ISA, though, such as kernel, debugger and other tools, that should be specified in an ABI.  Not our case, however.

**Comment by knightsifive** [comment]
I believe that our current consensus is a negative answer to this issue's question, i.e., no changes to the psABI are needed. I'll close this issue tomorrow if no dissenting opinions have been posted.
