### ISSUE TITLE
GPREL and TPREL register use

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-elf-psabi-doc#160]
The psABI has this to say about GPREL_I and GPREL_S:

---

**GP-Relative Relocations**: If `symbol` is within the range of a signed 12-bit immediate offset from `__global_pointer$`, then the address can be loaded with a single instruction which has one relocation, a `R_RISCV_GPREL_I` or `R_RISCV_GPREL_S`.

The instruction is an I-Type instruction (add immediate or load) with an `R_RISCV_GPREL_I` or an S-type instruction (store) with an `R_RISCV_GPREL_S` relocation. The following assembly show loading a gp-relative address:

```
     addi a0, gp, 0          # R_RISCV_GPREL_I (symbol)
```

This relies on the value of `__global_pointer$` being loaded into `gp` (aka `x3`). This can be used by linker relaxation to delete the `lui` instruction.

---

Note that nothing in there specifies that the gp register must be used until after a code sample is given that uses gp.  The simplest interpretation of the text in the psABI is that any register may be used with `R_RISCV_GPREL_I` and `R_RISCV_GPREL_S` relocations, as long as that register contains `__global_pointer$` prior to the relocated instruction.

ld.bfd implements something different:

https://github.com/riscv/riscv-elf-psabi-doc/blame/master/riscv-elf.md#L641-L655

ld.bfd has an undocumented feature: gprel relocations can be used to access the zero page (±2 KiB).  However, the way this is implemented overwrites `rs1` in any instruction which uses a gprel relocation, so `R_RISCV_GPREL_I` could not be used with `__global_pointer$` materialized in any other register.  TPREL functions similarly and overwrites rs1 with tp.

lld does not implement GPREL or TPREL at all.

---

Historically, conflicts between the psABI and binutils have been resolved in favor of binutils to avoid compatibility problems.  In this case, I think the compatibility concern is negligible; neither gcc nor clang generate GPREL_I, GPREL_S, TPREL_I, or TPREL_S relocations, and there is no assembly syntax for them, so the only way they could exist in object files is if someone else implemented object file writing against the ld.bfd source code while ignoring the psABI.

**I would like to add a sentence to the psABI stating that any register can be used with the short GPREL and TPREL relocations as long as that register holds the appropriate base value, and modify ld.bfd to support this.**  This is simpler to describe, simpler to implement, and provides some additional flexibility (the compact code model as currently proposed has a use case for this).

Yes/No?

**Comment by ebahapo** [comment]
I agree with you about generalizing the description of such relocations as just calculating the value of relocations relative to the `__global_pointer$` and the TLS area.  

Perhaps the sentence that specifies the value of the `gp` register could also be augmented to specify that it is the value of `__global_pointer$` only in the executable, with the intent to make it clear that DSOs should not rely on its value.

**Comment by jim-wilson** [comment]
ld.bfd can use these relocs for zero-page addressing, which has nothing to do with __global_pointer$.  This is an optimization.  And this is potentially useful for making weak symbols work though I don't think that we use it that way.  When resolving the reloc, if the address is gp relative, then we force the rs1 field to gp.  If the address is zero-page, then we force the rs1 field to x0.  There is no support here for using other registers as the base address.  It isn't clear how that could work. These GPREL relocs are only used for relaxation, so the linker has to rewrite the instruction, and we have to know what register to modify the instruction to use.

Maybe you are suggesting a non-relaxation case where the instruction already has the reloc created by the assembler, which put the right register in?  I suppose that could work.  We would have to change how relaxation works in ld.bfd, so that the right base register is written into the instruction when we change the reloc to a GPREL reloc, instead of when we resolve the reloc.  This would be necessary to avoid breaking the non-relaxation use of these relocs.  This sounds feasible.

But this does mean that the new use of GPREL relocs won't work with old ld.bfd versions, which could cause compatibility problems.  This could be tricky to solve.  We need linux distros to be updated to have a fixed ld.bfd before GCC or LLVM can use non-relaxation GPREL relocs, and we don't control the linux distros.  If this is tied to a particular code model, and only needs to work with linkers that support that code model that might be OK, except that we have no code model checks in the linker currently, so again, the current ld.bfd could fail.  This only works if we are guaranteed that the new non-relax GPREL reloc is always used with at least one reloc that the current ld.bfd does not support, as that would ensure an error, but I don't think it is safe to make that assumption.

Or we could just create a new reloc, with new name and number, and better defined semantics, and deprecate the old one.  This way there is no ABI break.

Same for the TPREL relocs, except that there is no zero-page/weak support, so we always write tp into the rs1 field when resolving the relocation, which would fail for any non-relaxation use that wants to use a different register.

**Comment by ebahapo** [comment]
Thank you for the extensive explanation, @jim-wilson.  When designing the proposal for the compact code model, I felt that it was necessary to create new `gp`-relative relocations implementing the same calculations as the existing ones, but opening up the possibility that they might have different semantics, especially with regards to their specific uses internally by the BFD linker.

**Comment by sorear** [comment]
@jim-wilson thank you for the clarification that applications other than ld should not generate these relocations.  In that case, we should IMO delete them from the psABI and reallocate the numbers as "reserved for internal use by linkers", since the psABI is an interface document, not a binutils internals document.
