### ISSUE TITLE
FP calling convention: no mention of unions in struct flattening description

### ISSUE THREAD

**Issue by asb** [riscv/riscv-elf-psabi-doc#24]
Consider the following declarations:

    struct s1_ty { float f; int i;  };
    struct s2_ty { float f; char c;  };
    union u_ty { struct s1_ty s1; struct s2_ty s2; };
    struct s3_ty { union u_ty u; };

As it stands, the FP calling convention makes no mention of unions. So if I had a function taking `u_ty` as an argument I might reasonably pass this according to the integer calling convention. If a function took `s3_ty`, there's a question of whether a union can ever be "flattened". For instance in this particular case, the first field of the union will always be a float. Presumably even if you did "flatten" the fp field, you'd still consider the second field of the flattened result to be a union of `int` and `char`, which would be an "aggregate" rather than an "integer". The degenerate case would be a union of two identical structs, containing a real and an integer.

I assume the intention is that unions are never "flattened"?

**Comment by asb** [comment]
Can someone please confirm the intended behaviour in these cases?

**Comment by jim-wilson** [comment]
On Thu, Nov 23, 2017 at 12:42 AM, Alex Bradbury <notifications@github.com>
wrote:

> Can someone please confirm the intended behaviour in these cases?
>

I can't talk about ABI intent, but I can talk about what the gcc port
does.  I see no special treatment for unions.

Given
struct s {
  union u {
    int i;
    float f;
  } u;
  float f;
};
float sub1 (struct s arg)
{
  return arg.u.f + arg.f;
}
I get
fmv.s.x fa5,a0
fmv.s.x fa4,a1
fadd.s fa0,fa5,fa4
So both fields were passed in integer registers.

One could treat the union as an integer field, and handle this struct as a
pair passed in one gpr and one fpr, but gcc does not do that.  Since fixing
gcc would require an ABI change, and an ABI change would be inconvenient,
it is probably best to clarify the ABI to mention that unions prevent a
struct from being flattened.  I suspect that is already the intent, since
if they wanted to handle unions here, they would have mentioned unions.

Jim

**Comment by palmer-dabbelt** [comment]
I think we should match what GCC is currently doing, which is to pass unions in X registers.  This currently even happens when there's only a single member in the union, and while it might have been worth changing this if we'd thought about it at the time I don't think it's worth an ABI break now.

````
union u0 {
  double f;
};

union u1 {
  double f;
};

double ufunc(union u0 a, union u1 b)
{
  return a.f + b.f;
}
````

````
ufunc:
	fmv.d.x	fa5,a0
	fmv.d.x	fa4,a1
	fadd.d	fa0,fa5,fa4
	ret
````

@aswaterman thoughts?

**Comment by aswaterman** [comment]
Passing unions in integer registers is a feature, as they are often used for type punning, so they’ll end up on the integer side anyway. Unions with only a single floating-point type are rare, so having a special case to pass those in float registers seems unnecessary. We should just document the current behavior.

**Comment by palmer-dabbelt** [comment]
OK, I think we're all in agreement here.  @asb: are you going to write the documentation?
