### ISSUE TITLE
double under -m32 -mfloat-abi=soft

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-elf-psabi-doc#6]
The same reasoning as for `long double` under `-m64` would apply here and double values, being = 2 * XLEN and > FLEN, should be passed exclusively in memory.

**Comment by aswaterman** [comment]
Agreed, these cases should be handled analogously.

One consideration is that passing by reference probably favors the case where the ABI is soft but hardware FP is available, whereas passing in two integer registers probably favors the case where hardware FP is not available.  Of course, I don't have data to substantiate that claim.

**Comment by aswaterman** [comment]
I looked into this briefly using a subset of SPEC CPU2006.

If you have the D extension but soft-float ABI, passing doubles by reference is fairly neutral to code size (all benchmarks within +/- 0.5%, with a median change of zero).  I don't have any data, but I expect that pass-by-reference will execute fewer dynamic instructions.

If you don't have the D extension, passing doubles by reference is bad for code size (median increase 5%, min 0%, max 80% (!)).  I'll follow up with an example that shows why.

**Comment by aswaterman** [comment]
Here is the example:

    double mulAdd(double x, double y, double z)
    {
      return y * z + x;
    }
    add   sp,sp,-16
    sw    ra,12(sp)
    sw    s0,8(sp)
    sw    s1,4(sp)
    mv    s0,a0
    mv    s1,a1
    mv    a0,a2
    mv    a1,a3
    mv    a2,a4
    mv    a3,a5
    call  __muldf3
    mv    a2,s0
    mv    a3,s1
    call  __adddf3
    lw    ra,12(sp)
    lw    s0,8(sp)
    lw    s1,4(sp)
    add   sp,sp,16
    jr    ra

Here is the by-reference code:

    add   sp,sp,-48
    sw    ra,44(sp)
    sw    s0,40(sp)
    sw    s2,36(sp)
    sw    s3,32(sp)
    mv    s0,a0
    lw    s2,0(a1)
    lw    s3,4(a1)
    lw    a0,0(a2)
    lw    a1,4(a2)
    lw    a4,0(a3)
    lw    a5,4(a3)
    sw    a0,16(sp)
    sw    a1,20(sp)
    sw    a4,8(sp)
    sw    a5,12(sp)
    add    a2,sp,8
    add    a1,sp,16
    add    a0,sp,24
    call   __muldf3
    lw    a4,24(sp)
    lw    a5,28(sp)
    sw    a4,8(sp)
    sw    a5,12(sp)
    sw    s2,0(sp)
    sw    s3,4(sp)
    mv    a2,sp
    add    a1,sp,8
    add    a0,sp,16
    call   __adddf3
    lw    a4,16(sp)
    lw    a5,20(sp)
    sw    a4,0(s0)
    sw    a5,4(s0)
    mv    a0,s0
    lw    ra,44(sp)
    lw    s0,40(sp)
    lw    s2,36(sp)
    lw    s3,32(sp)
    add   sp,sp,48
    jr    ra

**Comment by aswaterman** [comment]
It seems that GCC insists on creating a new stack slot when passing the arguments to muldf, rather than reusing the outer caller's stack slot and only passing the reference.  (Can we teach the compiler that the callee won't alter the arguments, so it's safe to pass by const reference, rather than creating a new copy of the value?)

The other inefficiency comes from the fact that it doesn't reuse the stack slot between muldf and adddf, so it has to copy muldf's result, taking another 4 instructions.

**Comment by aswaterman** [comment]
Seems a little weird to make ABI decisions because of compiler idiosyncrasies, but pragmatically, if GCC isn't going to optimize this code, then passing by reference is not a good idea.

**Comment by sorear** [comment]
@aswaterman It looks like SPARC says that arguments passed by reference belong to the callee and the caller must copy them, MIPS never passes arguments by reference (arbitrarily large structs are copied onto the stack), S390X arguments passed by reference belong to the *caller* and the callee must copy them, and AMD64 is silent on the matter.

**Comment by aswaterman** [comment]
Any idea how this manifests in the s390 GCC port?  Would be nice to run that experiment, too.

**Comment by aswaterman** [comment]
I think the right answer is to simplify the calling convention and pass RV32 doubles/RV64 quads in integer pairs.

My original argument behind passing quads by reference in RV64 was to better support systems that had Q hardware but preferred the RV64G ABI.  I'm now thinking that's misguided, since it penalizes what is probably the more common case of systems lacking Q hardware, yet doesn't do a great job for Q hardware, either.

In the HPC context, where people don't mind recompiling their code, folks will just use the Q ABI.

@kito-cheng

**Comment by sorear** [comment]
@aswaterman I agree.  gcc considers structs to be "TFmode" in some cases, so the long double handling is one of the more complicated bits currently, and if it turns out to not help I'm fine with it going.

**Comment by aswaterman** [comment]
OK, I'll prototype the change and run it through the regression tests.

**Comment by aswaterman** [comment]
done, https://github.com/riscv/riscv-gcc/commit/4b5e331c9d4da8cdcb55ec41a73585433c86eb57

**Comment by aswaterman** [comment]
I believe this is addressed.
