### ISSUE TITLE
 Floating-Point Control and Status Register (FCSR) not mentioned

### ISSUE THREAD

**Issue by sebhub** [riscv/riscv-elf-psabi-doc#72]
The  Floating-Point Control and Status Register (FCSR) contains reserved bits, the rounding mode (frm) and the accrued exception flags (fflags).

The frm are probably a system-wide setting.

What about the fflags? Are they supposed to be preserved across function calls?

**Comment by aswaterman** [comment]
fflags are basically a global variable, so they don't need to be saved or restored on calls/returns.  This follows the C11 fenv convention.

**Comment by sebhub** [comment]
Ok, so from C11 fenv it follows that this is a thread-local variable?

**Comment by jim-wilson** [comment]
In glibc, fesetexceptflags, feclearexcept, fetestexcept etc all access fflags directly.  It is the job of the kernel to ensure that each process has its own copy of fcsr, which is why this is part of the process context in the linux kernel.  It would be the job of the thread package to save/restore fflags if not using processes.  The glibc makecontext, swapcontext, etc calls also save/restore fcsr which would solve that problem.  glibc has lots of math tests, some of which use threads, and they work on linux, so the linux/glibc support for this appears to be good.  RTEMS can probably do something similar.

**Comment by sebhub** [comment]
Thanks for the clarification. I created a pull request to somehow add this information to the psABI document.

https://github.com/riscv/riscv-elf-psabi-doc/pull/73
